### ISSUE TITLE
Sign up and login not view able.

### ISSUE THREAD

**Issue by Nordeast** [anthonyto/Zapskills#32]
When the browser is resided to half a full screen the login and sign up buttons disappear.

**Comment by anthonytokosky** [comment]
Can you Include a screenshot?

**Comment by Nordeast** [comment]
![buttons](https://cloud.githubusercontent.com/assets/8978368/7362753/d71f8536-ed33-11e4-8587-bd89f65ed3ea.PNG)

**Comment by anthonytokosky** [comment]
Resolved in 8ec2fa475bbdc87ca29a234be6608f397311af94

**Comment by shachiagarwalla** [comment]
I can still see the issue.
![screen shot 2015-05-02 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/8856302/7441933/46c265c4-f0c3-11e4-903c-4cb1d6a67a44.png)

**Comment by anthonytokosky** [comment]
Resolved
